<?php

return [
    'title' => 'MyDrive 5.0',
    'login' => 'użytkownik',
    'password' => 'hasło',
    'logInBtn' => 'Zaloguj',
    'logInErr' => 'Nieodpowiednie hasło lub nazwa użytkownika!',
    'logInWrongPswd' => 'Nieprawidłowe hasło!',
    'inputChars' => 'A-Za-z0-9',
    'inputCharsHtmlTitle' => 'znaki: cyfry, litery alfabetu łacińskiego (od 6 do 36)',
    'inputMinLen' => 6,
    'inputMaxLen' => 36,
    'userNotFound' => 'Użytkownik %s nie istnieje!',
    'authMethodOtp' => 'OTP',
    'authMethodPswd' => 'hasło',
    'timeHiddenID' => 'sessionTime',
    'timerID' => 'sessionTimer',
    'modalDivID' => 'modalDiv',
    'sessionProlongTitle' => 'Przedłużenie sesji użytkownika',
    'closeBtnText' => 'Zamknij',
    'tryProlong' => 'Spróbuj przedłużyć',

    'userDataTitle' => 'Dane użytkownika',
    'userDataAuthMethod' => 'Metoda logowania',
    'userDataUsername' => 'Nazwa użytkownika',
    'userDataUpdatedAt' => 'Aktualizacja danych',
    'userDataCreatedAt' => 'Utworzenie konta',
    'userDataLastActivity' => 'Ostatnia aktywność',
    'userDataStorage' => 'Zajęte miejsce',

    'uploadTitle' => 'Przesyłanie plików (do&nbsp;64MB)',
    'uploadBtn' => 'Spróbuj przesłać',
    'uploadLimit' => (64 * 1024 * 1024),
    'uploadChoose' => 'wybierz plik',
    'uploadChosenName' => 'wybrany plik',
    'uploadChosenSize' => 'rozmiar',
    'uploadErrorInfo' => 'W czasie przesyłania pliku wystąpił błąd.',
    'uploadSuccessInfo' => 'Plik \'%s\' o rozmiarze %s został zapisany.',
    'uploadSizeProblem' => 'Nieodpowiedni rozmiar pliku.',
    'uploadMimeProblem' => 'Niedozwolony format pliku (%s).',
    'storageLimitProblem' => 'Za mało wolnego miejsca na dane (zabrakło %s).',
    'filesContentHashID' => 'contentHashValue',
    'properties' => 'Właściwości &nbsp;📃',
    'actions' => 'Czynności &nbsp;🛠️',
    'lastModified' => 'czas: &nbsp;',
    'fileSize' => 'rozmiar: &nbsp;',
    'filename' => 'nazwa: &nbsp;',
    'actionShare' => 'Udostępnij plik',
    'actionDownload' => 'Pobierz plik',
    'actionRename' => 'Zmień nazwę',
    'actionDelete' => 'Usuń plik',
    'fileActionID' => 'fileActionID',
    'fileActionOkID' => 'fileActionOkID',
    'fileActionErrID' => 'fileActionErrID',
    'downloadOkInfo' => 'Za chwilę rozpocznie się pobieranie wybranego pliku.',
    'downloadErrInfo' => 'Nie udało się pobrać wybranego pliku.',
    'renameTitle' => 'Zmiana nazwy',
    'renameOldNameLabel' => 'Obecna nazwa &nbsp;<span style="font-size: 115%;">&#x24d8;</span>',
    'renameNewNameLabel' => 'Proponowana nazwa &nbsp;<span>✏️<span>',
    'renameCleanLabel' => 'Ostateczna nazwa &nbsp;<span style="font-size: 115%;">&#x24d8;<span>',
    'renameCleanPlaceholder' => 'nazwa&nbsp;po&nbsp;oczyszczeniu',
    'tryRename' => 'Spróbuj zmienić',
    'renameErrInfo' => 'Nie udało się zmienić nazwy wybranego pliku.',
    'renameOkInfo' => 'Nowa nazwa: %s',
    'deleteTitle' => 'Usuwanie plików',
    'deleteQuestionText' => 'Czy na pewno chcesz usunąć ten plik?',
    'deleteErrInfo' => 'Nie udało się usunąć wybranego pliku.',
    'deleteOkInfo' => 'Plik został usunięty.',
    'tryDelete' => 'Spróbuj usunąć',
    'storageLimit' => 100 * 1024 * 1024,
    'storageInfoFormat' => '%s z %s (%s%%)',
    'shareTitle' => 'Udostępnianie',
    'shareUsernamePlaceholder' => 'nazwa użytkownika',
    'shareErrInfo' => 'Nie udało się udostępnić wybranego pliku.',
    'shareOkInfo' => 'Plik %s został udostępniony użytkownikowi %s.',
    'tryShare' => 'Udostępnij',
    // Insufficient storage!

    'homePage' => '/',
    'noscriptRedirect' => '/javaScriptDisabled',
    'authentication' => '/authentication',
    'drive' => '/drive',
    'prolongPost' => '/prolong',
    'logout' => '/logout',
    'upload' => '/upload',
    'display' => '/display',
    'download' => '/download',
    'rename' => '/rename',
    'clean' => '/clean',
    'checkCSRF' => '/checkCSRF',
    'delete' => '/delete',
    'share' => '/share',

    'err001' => 'err001',
];
